version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cloudsphere_hrms

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend

    ports:
      - "5000:5000"

    depends_on:
      - mysql

  frontend:
    build: ./frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  mysql_data: